/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface CDelegationStorageInterface extends Interface {
  functions: {
    implementation: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class CDelegationStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): CDelegationStorage;
  attach(addressOrName: string): CDelegationStorage;
  deployed(): Promise<CDelegationStorage>;

  on(event: EventFilter | string, listener: Listener): CDelegationStorage;
  once(event: EventFilter | string, listener: Listener): CDelegationStorage;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): CDelegationStorage;
  removeAllListeners(eventName: EventFilter | string): CDelegationStorage;
  removeListener(eventName: any, listener: Listener): CDelegationStorage;

  interface: CDelegationStorageInterface;

  functions: {
    implementation(): Promise<string>;
  };

  implementation(): Promise<string>;

  filters: {};

  estimate: {
    implementation(): Promise<BigNumber>;
  };
}
