/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface CErc20StorageInterface extends Interface {
  functions: {
    underlying: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class CErc20Storage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): CErc20Storage;
  attach(addressOrName: string): CErc20Storage;
  deployed(): Promise<CErc20Storage>;

  on(event: EventFilter | string, listener: Listener): CErc20Storage;
  once(event: EventFilter | string, listener: Listener): CErc20Storage;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): CErc20Storage;
  removeAllListeners(eventName: EventFilter | string): CErc20Storage;
  removeListener(eventName: any, listener: Listener): CErc20Storage;

  interface: CErc20StorageInterface;

  functions: {
    underlying(): Promise<string>;
  };

  underlying(): Promise<string>;

  filters: {};

  estimate: {
    underlying(): Promise<BigNumber>;
  };
}
