/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractFactory, Signer } from "ethers";
import { Provider } from "ethers/providers";
import { UnsignedTransaction } from "ethers/utils/transaction";

import { TokenErrorReporter } from "./TokenErrorReporter";

export class TokenErrorReporterFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(): Promise<TokenErrorReporter> {
    return super.deploy() as Promise<TokenErrorReporter>;
  }
  getDeployTransaction(): UnsignedTransaction {
    return super.getDeployTransaction();
  }
  attach(address: string): TokenErrorReporter {
    return super.attach(address) as TokenErrorReporter;
  }
  connect(signer: Signer): TokenErrorReporterFactory {
    return super.connect(signer) as TokenErrorReporterFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenErrorReporter {
    return new Contract(address, _abi, signerOrProvider) as TokenErrorReporter;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "error",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "info",
        type: "uint256"
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "detail",
        type: "uint256"
      }
    ],
    name: "Failure",
    type: "event"
  }
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603e80601d6000396000f3fe6080604052600080fdfea265627a7a72315820d2c05204d9d9d0a6265a61ba00ad65d3f9012e4a7412488a17b4950acb94e8b764736f6c63430005100032";
